name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  branch:
    required: true
    description: 'the branch name to be saved to the API'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
